apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elk
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    name: rest
    protocol: TCP
  - port: 9300
    name: inter-node
    protocol: TCP
  type: ClusterIP
