apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.13.0
          ports:
            - containerPort: 5044
          env:
            - name: ELASTIC_USERNAME
              value: "elastic"
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elk-credentials
                  key: elastic-password
          volumeMounts:
            # Mount only the pipeline config
            - name: pipeline-config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            # Mount the logstash.yml separately
            - name: logstash-yml
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
      volumes:
        - name: pipeline-config
          configMap:
            name: logstash-config
            items:
              - key: logstash.conf
                path: logstash.conf
        - name: logstash-yml
          configMap:
            name: logstash-config
            items:
              - key: logstash.yml
                path: logstash.yml
