apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    app: logstash
  ports:
  - port: 5044
    targetPort: 5044
    protocol: TCP
    name: beats
  type: NodePort
